name: allo_urgence_pro
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  font_awesome_flutter: ^10.5.0
  get: 4.6.5
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.4.0
  http: ^1.1.0
  image_picker: ^1.0.2
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  syncfusion_flutter_pdfviewer: ^22.2.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
